Dcm kit glossary content
ClosedSourcerer/eclipse-tractusx.github.io pull request #10
Opened 2024-09-27 12:31 UTC by lanfrans

please review!

2024-09-30 08:42 UTC, ClosedSourcerer requested changes

2024-09-30 08:42 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|WeekBasedCapacityGroup|This term refers to the specific WeekBasedCapacityGroup object defined in this standard.|
Keep the camel casing consistent please.

>Business application provider
>Calendar Week
>(Simulated) Delta-Production
>(Material) demand
>Demand fluctuation
>Demand Deviation

2024-09-30 08:42 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|One-up|Used in DCM context as synonymous of “customer”|
Either `Used in DCM context synonymous with “supplier”`

or `Used in DCM context as synonym of “supplier”`

or even shorter: `used synonymously with "supplier"` the DCM context is not really required.

2024-09-30 08:42 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|API|Application Programming Interface is a set of rules, protocols, and tools for building software and applications. Examples for DCM can be found here: https://eclipse-tractusx.github.io/docs-kits
To improve aesthetics it might be interesting to format links as such:


[LinkText](https://eclipse-tractusx.github.io/docs-kits/next/kits/DCM-Kit/development-view/overview#apis-utilized-by-a-dcm-application)

`[LinkText](https://eclipse-tractusx.github.io/docs-kits/next/kits/DCM-Kit/development-view/overview#apis-utilized-by-a-dcm-application)`

2024-09-30 08:42 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|Supplier|A role within the DCM use case, which represents a company that supplies goods to its customers. Participating companies can have multiple roles at the same time. Suppliers provide consiste
Either "synonymous with one-down"
or "Synonym: one-down"

Applies multiple times within the glossary.

2024-09-30 08:42 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|WeekBasedCapacityGroup|This term refers to the specific WeekBasedCapacityGroup object defined in this standard.|
Any reason why the other aspect models (especially WeekBasedMaterialDemand) do not have an entry of their own?

2024-09-30 08:42 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|Demand fluctuation|A systematical measure to track fluctuation in demand in a given period and it intends to point out be stability or even the best forecast available. One of the metrics used to me
Both demand deviation and fluctuation are not present in the KIT (expects for the glossary).
If they get added by another feature, making them relevant --> OK
If not, those entries should be removed.

2024-09-30 09:34 UTC, lanfrans commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|WeekBasedCapacityGroup|This term refers to the specific WeekBasedCapacityGroup object defined in this standard.|
no  reason why it is missing... I will add it...

2024-09-30 09:42 UTC, lanfrans commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|Demand fluctuation|A systematical measure to track fluctuation in demand in a given period and it intends to point out be stability or even the best forecast available. One of the metrics used to me
Demand deviation is a term listed in the glossary as part of the standard document (Chapt. 1.5) - we should keep it for consistency. 
Demand fluctuation can be removed.
OK for you?

2024-09-30 11:07 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|Demand fluctuation|A systematical measure to track fluctuation in demand in a given period and it intends to point out be stability or even the best forecast available. One of the metrics used to me
Yes

2024-10-01 06:54 UTC, lanfrans commented
Hi @ClosedSourcerer , requested changes were resolved. Final review requested. Thx!

2024-10-02 08:13 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +- SPDX-FileCopyrightText: 2023,2024 Contributors to the Eclipse Foundation
The glossary is completely new.
--> Remove reference to 2023
--> Remove all companies that have not contributed content. (e.g. Fraunhofer)
Contribution might have happened while working on the feature, during opendiscussions / workshop or during the review itself. Doing technical translations is not IP contribution, unless a new file gets created through it.

2024-10-02 12:49 UTC, lanfrans commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +- SPDX-FileCopyrightText: 2023,2024 Contributors to the Eclipse Foundation
--> Remove reference to 2023 - done.
--> Remove all companies that have not contributed content. (e.g. Fraunhofer) - Does it make sense to simply list all companies that are part of the EG, indipendently if they have given a small or lage contribution?

2024-10-02 12:52 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +- SPDX-FileCopyrightText: 2023,2024 Contributors to the Eclipse Foundation
> --> Remove reference to 2023 - done. --> Remove all companies that have not contributed content. (e.g. Fraunhofer) - Does it make sense to simply list all companies that are part of the EG, indipendently if they have given a small or lage contribution?

According to the preliminary answers to my licensing questions: No, IP contributions and hence licensing mentions have to be tracked on a per file level and depending on the exactt level of involvment. Just being part of the Expert Group does not result in a relevant IP claim.

https://github.com/orgs/eclipse-tractusx/projects/61?pane=issue&itemId=78837856

2024-10-08 12:17 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|Customer|A role within the DCM use case, which represents a company that receives goods from its suppliers. Participating companies can have multiple roles at the same time: in this context, A custo
typo "customers" instead of customer"

2024-10-08 12:21 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|Demand fluctuation|A systematical measure to track fluctuation in demand in a given period and it intends to point out be stability or even the best forecast available. One of the metrics used to me
as per current discussion, there is a chance thtat "demand fluctuation" may be replaced by "demand volatility" to ensure consistency between DCM Kit and DCM standard. Final decision is not taken yet, but hopeuflly by end of this week.

2024-10-09 09:47 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|Demand fluctuation|A systematical measure to track fluctuation in demand in a given period and it intends to point out be stability or even the best forecast available. One of the metrics used to me
@Frank-Globisch I agree. In that case you do not touch the standard and that is the best option

2024-10-11 12:19 UTC, KZI-CatX approved these changes

2024-10-11 18:28 UTC, AnastasiaNogay commented
Reviewed!

2024-10-14 08:59 UTC, reginePrivat approved these changes
mein erster review - passt alles

2024-10-14 16:16 UTC, lanfrans commented
[like]  Stefania Lanfranchini reacted to your message:
________________________________
From: Regine ***@***.***>
Sent: Monday, October 14, 2024 9:00:15 AM
To: ClosedSourcerer/eclipse-tractusx.github.io ***@***.***>
Cc: Stefania Lanfranchini ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [ClosedSourcerer/eclipse-tractusx.github.io] DCM KIT Glossary Content (PR #10)


@reginePrivat approved this pull request.

mein erster review - passt alles

—
Reply to this email directly, view it on GitHub<https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/pull/10#pullrequestreview-2365849864>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AY5IHOXOT2GHMYMBNIPOXVDZ3OBZ7AVCNFSM6AAAAABO7CHEE6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNRVHA2DSOBWGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-10-15 07:52 UTC, lanfrans commented
@Frank-Globisch and @cka159 : can you please provide me with the final definition of Demand Volatility to be added in the Glossary? Thx!

2024-10-15 09:13 UTC, LukasSchmetz commented
@lanfrans Porposal: 
| Demand volatility | Demand volatility help suppliers to identify and measure volatility in demands. It allows them to address demand volatility directly to their customers, increasing transparency for a more effective collaborative capacity planning. Demand deviation is the first metric for measuring demand volatility. |

@cka159 @Frank-Globisch : We used our definition from the Demand Volatility chapter to have it fully consistent. Fine for you?

2024-10-15 09:27 UTC, kenobi79 approved these changes

2024-10-15 12:50 UTC, lanfrans commented
Demand Deviation definition added as per @LukasSchmetz suggestion above.

2024-10-15 13:06 UTC, lanfrans commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/glossary.md
> +|Demand fluctuation|A systematical measure to track fluctuation in demand in a given period and it intends to point out be stability or even the best forecast available. One of the metrics used to me
Demand Fluctuation was dismissed; Demand Volatility was added - see https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/pull/10#issuecomment-2413828210

2024-10-16 14:47 UTC, LukasSchmetz commented
Minor consistency topics updated via commit b31dafe

2024-10-16 14:48 UTC, LukasSchmetz approved these changes
LGTM

2024-10-16 15:02 UTC, MWADCM approved these changes

2024-10-16 16:16 UTC, Frank-Globisch commented
Fine with the suggested and used Demand Volatilty description by @LukasSchmetz

2024-10-17 11:09 UTC, pdequick approved these changes
ok

2024-10-17 15:05 UTC, KaQuSTLA commented
LGTM I just find time to checked the changes done.

2024-10-18 09:18 UTC, ClosedSourcerer approved these changes

2024-10-21 07:29 UTC, merged