Dcm kit general updates
ClosedSourcerer/eclipse-tractusx.github.io pull request #11
Opened 2024-09-27 12:51 UTC by pdequick

2024-09-27 12:59 UTC, KaQuSTLA approved these changes

2024-09-30 08:03 UTC, ClosedSourcerer requested changes
I picked out a few examples. Please Update the content to ensure consistency within itself as well as the existing KIT and standard content.

2024-09-30 08:03 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +If so, Actual and Maximum Capacity measures must be updated to reflect the result of the collaboration. As a result, the bottleneck disappears, as exemplified in graph 4b below.
What are actual and maximum capacity measures and how can they be updated?
The standard does not have an aspect model that defines measures, that could be updated.

Maybe measures that do affect actual and maximum capacity need to be implemented?

2024-09-30 11:47 UTC, ClosedSourcerer requested changes

2024-09-30 11:47 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +#### Exemple 2: Imbalance
And Exemple 3 instead of Example 3

2024-10-02 08:26 UTC, ClosedSourcerer commented
I am pretty sure Renault contributed. Please adopt the License Notice accordingly.

2024-10-02 08:27 UTC, ClosedSourcerer commented
> I am pretty sure Renault contributed. Please adopt the License Notice accordingly.

Also all the license files for the pictures are empty.
Please add a license notice.

2024-10-08 07:29 UTC, ClosedSourcerer requested changes
Please approach the license notice with the gravitas it deserves. 

https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-00

2024-10-08 07:29 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/resources/business-process_capacity-types_example1.svg.license
> +- SPDX-FileCopyrightText: 2023,2024 Renault SAS
This file is new.
How come the years mentioned include 2023?
Did Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V (Fraunhofer) really contribute to the picture the license file is covering?
Same question for all other companies.

--> The license notice is unfortunately not a simple matter of copy paste.

2024-10-08 13:36 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure: *Visualizing Capacity and Demand*
suggested to have a more descriptive figure description, e.g. in this case something like "Demand-Capacity situation with full saturation"

2024-10-08 13:37 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure: *Visualizing Capacity and Demand*
suggested to have a more descriptive figure description, e.g. in this case something like "Demand-Capacity situation with imbalances"

2024-10-08 13:38 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure: *Visualizing Capacity and Demand*
suggested to have a more descriptive figure description, e.g. in this case something like "Simple Demand-Capacity situation without bottlenecks"

2024-10-08 13:39 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure: *Visualizing Capacity and Demand*
suggested to have a more descriptive figure description, e.g. in this case something like "Resolving imbalances in Demand-Capacity situation"

2024-10-08 13:44 UTC, Frank-Globisch requested changes
reviewed updates - overall fine with minor remarks & suggestions particularly for figure descriptions

2024-10-09 09:43 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure: *Visualizing Capacity and Demand*
Also important: No new Naming - Saturation!

2024-10-10 11:40 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +The supplier on the other hand has more options to solve problems. They can not only increase and decrease capacity quantities, but also use Flexible Capacity, load factors and delta production.
I would use capital letters in case a feature is mentioned and link it directly to the respective chapter: Load Factors, simulated Delta-Production (as written in Delta-Production chapter).

2024-10-10 11:41 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +![Capacity Example](./resources/business-process_capacity-types_example1.svg)
Actual Capacity and Maximum Capacity (consistency)

2024-10-10 11:42 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure:
needs to be removed here between figure and legend and several cases are not existing here (should we keep it then to have same legend for all example figures?)

2024-10-10 11:43 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure: *Visualizing Capacity and Demand*
Several cases are not existing here as only "demand within actual capacity" exists (should we keep it then to have same legend for all example figures?)

2024-10-10 11:52 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Though no lack of capacity is detected, even a slight increase of Demand could not be managed.  Both Supplier and Customer can conclude, that it may be relevant to collaborate to identify measures to
"Both, Supplier and Customer, can conclude,..."

2024-10-10 11:54 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +If so, Actual and Maximum Capacity must be updated to reflect the result of the collaboration. As a result, the bottleneck disappears, as exemplified in graph 4b below.
Example 4b

2024-10-10 11:55 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
Figure name is missing

2024-10-10 11:56 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
>  |Properties|Description|
Keep Table Header consistent with other chapter

| Main Parameters | Required? | Description | Example |
| - | - | - | - |

2024-10-10 11:59 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> -|Maximum Capacity|The supplier's maximum capacity is the maximal available output per calendar week and material for a specific customer in a specific unit of measure. The maximum capacity thereby re
consistency! "Supplier" "Customer" "Maximum Capacity" "Flexible Capacity" " Actual Capacity" "Capacity Group"

2024-10-10 12:02 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
>  |Point in Time|ISO Calendar Week of the given time series entry. UstIt must be given as a date of the Monday in the week.|
Typo "UstIt"

2024-10-10 12:03 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +|Actual Capacity|The Actual Capacity is the realistically planned output per calendar week and material for a specific customer in a specific unit of measure, considering all positive or negative imp
Consistency e.g. "Customer" "Capacity"

2024-10-10 12:04 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +|Actual Capacity|The Actual Capacity is the realistically planned output per calendar week and material for a specific customer in a specific unit of measure, considering all positive or negative imp
Please check for whole document and following descriptions

2024-10-11 06:29 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure:
Need to unify image description

2024-10-11 06:33 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +When matching Demand to Capacity, one will see that
maybe: "it is recognizable"

2024-10-11 06:37 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
>  |Point in Time|ISO Calendar Week of the given time series entry. UstIt must be given as a date of the Monday in the week.|
This I do not understand  - @LukasSchmetz Typo "UstIt"?

2024-10-11 12:18 UTC, KZI-CatX approved these changes

2024-10-11 12:41 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +![Capacity Example](./resources/business-process_capacity-types_example1.svg)
Fixed via https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/commit/0beec48c39988251edb354c69d54437e3d7b15e8

2024-10-15 09:28 UTC, kenobi79 approved these changes

2024-10-15 15:37 UTC, reginePrivat commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
line 92: "......keeping it up to date" (instead of  ".. up to datA")

2024-10-16 07:21 UTC, reginePrivat approved these changes

2024-10-16 15:37 UTC, MWADCM approved these changes

2024-10-17 10:19 UTC, pdequick commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
>  |Point in Time|ISO Calendar Week of the given time series entry. UstIt must be given as a date of the Monday in the week.|
uPPER case issues sovled

2024-10-17 10:29 UTC, pdequick reviewed
all license files within scope of this feature  should be ok now

2024-10-17 10:29 UTC, pdequick commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure: *Visualizing Capacity and Demand*
legend updated for all figures with upper case (SVG updated)

2024-10-17 14:10 UTC, LukasSchmetz reviewed
LGTM! Corrections of agreed terminology in lower cases (e.g. "customer" or "supplier" and missing figure descriptions fixed. Licensing topic to be clarified.

2024-10-17 14:11 UTC, LukasSchmetz approved these changes
LGTM! Corrections of agreed terminology in lower cases (e.g. "customer" or "supplier") and missing figure descriptions fixed. Licensing topic to be clarified.

2024-10-17 14:43 UTC, KaQuSTLA approved these changes

2024-10-17 16:43 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure: *Visualizing Capacity and Demand*
great thx

2024-10-17 16:44 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure: *Visualizing Capacity and Demand*
great, thx

2024-10-17 16:44 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure: *Visualizing Capacity and Demand*
great thx

2024-10-17 16:44 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
> +Figure: *Visualizing Capacity and Demand*
great, thx

2024-10-17 16:45 UTC, Frank-Globisch approved these changes
all requested changes have been covered - thank you

2024-10-18 12:06 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/business-process.md
test

2024-10-21 07:12 UTC, merged