DCM kit delta production content
ClosedSourcerer/eclipse-tractusx.github.io pull request #16
Opened 2024-10-02 13:57 UTC by kenobi79

2024-10-07 09:25 UTC, ClosedSourcerer requested changes
The Background of the KIT is #000000
Plase have a look at the License Notice as well.  I am kinda missing capgemini in there.

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> -## Sequence Diagram
mermaid sequence DIagram does work with the Docusaurus Version 2. No reason to replace it with a picture.

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- Solve minor bottlenecks via pre production
Table above mentiones post production as a capability, but only pre production can solve bottleneckes here?
--> Concistency

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +![Untitled diagram-2024-10-02-134301](https://github.com/user-attachments/assets/92d2f3ef-ae30-4d16-8522-445419f97974)
Pictures and a corresponding license files need to go here: docs-kits\kits\Demand and Capacity Management Kit\adoption-view\use-case\resources

Do not copy paste pictures into the KIT.

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +Figure: *Capacity group structure with linked material demand incl. delta production result*
Is it really worth to abbreviate including ?

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +```json
Nope:

`deltaProductionResult`

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +Simulated Delta-Production may be used within a Capacity Group to indicate how production can be adjusted to meet demand. It helps cover potential shortfalls by showing where goods could be produced
pre-production and post-production and Delta-Production.

What makes Delta-Production worth Camel-Casing, but post-production and pre-production not?

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +| Main Parameters | Required? | Description | Example |
Required? vs. Mandatory?

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +| Delta Production Result | no | Delta related to the aggregated material demand after pre-/post production calculation the supplier wants to send to the customer. Can be positive and negative.| Deci
no instead of No
Why do the values for column 2 start with a small letter where the others always start with a capital letter?

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- The standard does not provide individual calculation logic for delta production, only the results may be transferred
Provide and consume are used to denote data transfers.

A the same time transfer is used in this sentence. 

However the standard itself is not used to transfer / provide data. It only describes aspect models. 
--> Whole sentence needs to be carefully reformulated.

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- Calculation automation and smoothing logic is subject to suppliers individual planning requirements and tools
I consider `smoothing logic` a problematic expression.
Yes, you can smooth data and smoothing is the correct term. However it is usually not used in combination with `logic`
Also: The automation of what calculation? The smoothing logic?

Consider: `Suppliers should to apply appropriate smoothing algorithms, depending on their planning requirements and toolchain`

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +![DeltaProduction_swimlane](https://github.com/user-attachments/assets/410b2f1d-ae93-4fff-8842-2214bfcbd99d)
See above: Do not copy paste pictures into the KIT

2024-10-07 09:25 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +![DCM_DeltaProduction](https://github.com/user-attachments/assets/4d27b7c8-bd66-4222-9870-3b4176b4459d)
See above: Do not copy paste pictures into the KIT

2024-10-07 09:46 UTC, ClosedSourcerer requested changes

2024-10-07 09:46 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> -## Sequence Diagram
Also: Deleting the heading ## Sequence Diagram was most likeley not intended. Please restore it.

2024-10-07 09:46 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +![DCM_DeltaProduction](https://github.com/user-attachments/assets/4d27b7c8-bd66-4222-9870-3b4176b4459d)
Unabhängig davon: Das Bild selbst finde ich sehr gelungen

2024-10-08 10:25 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +![Untitled diagram-2024-10-02-134301](https://github.com/user-attachments/assets/92d2f3ef-ae30-4d16-8522-445419f97974)
Added all images to /resources incl. license file. Changed all image links to correct path.

2024-10-08 10:26 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +![DeltaProduction_swimlane](https://github.com/user-attachments/assets/410b2f1d-ae93-4fff-8842-2214bfcbd99d)
Added all images to /resources incl. license file. Changed all image links to correct path.

2024-10-08 10:45 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> -## Sequence Diagram
## Sequence Diagram restored

2024-10-08 10:47 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- Solve minor bottlenecks via pre production
added post production

2024-10-08 10:48 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +Figure: *Capacity group structure with linked material demand incl. delta production result*
changed

2024-10-08 10:48 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +Simulated Delta-Production may be used within a Capacity Group to indicate how production can be adjusted to meet demand. It helps cover potential shortfalls by showing where goods could be produced
changed

2024-10-08 10:49 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +| Main Parameters | Required? | Description | Example |
changed

2024-10-08 12:16 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- The standard does not provide individual calculation logic for delta production, only the results may be transferred
changed to: The standard does not define [...], only the results may be submitted

2024-10-08 12:16 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- Calculation automation and smoothing logic is subject to suppliers individual planning requirements and tools
considered and adopted

2024-10-08 13:10 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
>  |Inform customer||X|
it seems like individual line for pre-production was replaced by combined "pre-/post production, however also additional line for post production still appears to be there. Please check and in case doubled remove the individual line.

2024-10-08 13:18 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +Suppliers can use comments to provide customers with additional information about the simulated Delta-Production. For more details on this communication feature, see Chapter 5.9 in the CX-0128 DCM St
suggestion to add link to standard library DCM file online.

2024-10-08 13:22 UTC, Frank-Globisch requested changes
please review my individual in-line comments and update particularly based on agreed general rules as documented in MIRO.

2024-10-09 09:32 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +| Delta Production Result | no | Delta related to the aggregated material demand after pre-/post production calculation the supplier wants to send to the customer. Can be positive and negative.| Deci
Classical Case and reason for adjustment EG

2024-10-10 11:06 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- Solve minor bottlenecks via pre production
Don´t know if I am wrong but in the Delta production branch document I still don´t see Post production

Furthermore I would always name it as "pre-production/post-production" using the dash in between as in "Delta-Production". Different ways how it is written throughout the document (see e.g. figure description of the bar chart example)

2024-10-10 11:07 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +```json
I would suggest just to write "...capacity data via the parameter: 
Then put directly the table and remove the codeblock as I think it is redundant (same as we did for load factor chapter

2024-10-10 11:08 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +"deltaProductionResult"
proposal to remove and just use tabke below

2024-10-10 11:08 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +| deltaProductionResult | No | Delta related to the aggregated material demand after pre-/post production calculation the supplier wants to send to the customer. Can be positive and negative.| Decima
Proposal to use preferred name from data model "Delta Production Result". Added for consistent discussion to our weekly already for tomorrow

2024-10-10 11:11 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- The standard does not define individual calculation logic for delta production, only the results may be submitted
Delta-Production (consistency)

2024-10-11 06:24 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +| deltaProductionResult | No | Delta related to the aggregated material demand after pre-/post production calculation the supplier wants to send to the customer. Can be positive and negative.| Decima
Recommendation: "pre-producton 400"

2024-10-11 10:01 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +#### Sequence Diagram
Heading jumps two levels instead of one...

2024-10-11 12:17 UTC, KZI-CatX approved these changes

2024-10-15 09:09 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +Suppliers can use comments to provide customers with additional information about the simulated Delta-Production. For more details on this communication feature, see Chapter 5.9 in the CX-0128 DCM St
Done

2024-10-15 09:10 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +#### Sample Data
Done

2024-10-15 09:10 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +"deltaProductionResult"
Done

2024-10-15 09:11 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- The standard does not define individual calculation logic for delta production, only the results may be submitted
Done

2024-10-15 09:22 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- Solve minor bottlenecks via pre production
Checked for consistency throughout ("Simulated Delta-Production"). For figure description kept only "pre-production", as figure does not show "post-production"

2024-10-15 09:23 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> -## Sequence Diagram
Sequence diagram moved to example area

2024-10-15 11:08 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
>  |Function / Role|Customer|Supplier|
In the sentence prior to the roles and functions table it needs to be "Delta-Production" due to consistency with the remaining chapter

2024-10-15 11:57 UTC, LukasSchmetz approved these changes
LGTM

2024-10-15 15:22 UTC, reginePrivat approved these changes

2024-10-15 15:22 UTC, reginePrivat commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +Simulated  is a feature that helps suppliers to manage their production capacity more effectively. It allows them to address and balance capacity shortages without having to increase their actual or
maybe I missed the discussion... : But I thought there must be written "Simulated Delta-Produktion" ( The word "Delta-Production" is missing)

This also applies to the following sentences.....

2024-10-16 07:31 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +Simulated  is a feature that helps suppliers to manage their production capacity more effectively. It allows them to address and balance capacity shortages without having to increase their actual or
Thx Regine, it was a mistake using "replace all" :-) Corrected.

2024-10-16 12:13 UTC, ClosedSourcerer requested changes

2024-10-16 12:13 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +<img src="https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/blob/DCM-KIT-Load-Factors-Content/docs-kits/kits/Demand%20and%20Capacity%20Management%20Kit/adoption-view/use-case/resources/bu
This break the Docusaurs. Also business-process_FunctionalBlockDiagram_Legend.svg is not part of this Branch (Delta Production) but rather part of the Load-Factor Branch

2024-10-16 12:44 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +<img src="https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/blob/DCM-KIT-Load-Factors-Content/docs-kits/kits/Demand%20and%20Capacity%20Management%20Kit/adoption-view/use-case/resources/bu
commented out, added business-process_FunctionalBlockDiagram_Legend.svg to Delta Production Branch, added relative path to legend image. Can't get scaling to work though, please suggest how this should be done. Thx

2024-10-17 04:37 UTC, MWADCM approved these changes

2024-10-17 11:59 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +<img src="https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/blob/DCM-KIT-Load-Factors-Content/docs-kits/kits/Demand%20and%20Capacity%20Management%20Kit/adoption-view/use-case/resources/bu
Just delpoy the KIT. It scales it to an acceptable level.
![image](https://github.com/user-attachments/assets/6153e328-ec03-4bbe-a435-ddf210ba04ac)

2024-10-17 15:44 UTC, lanfrans approved these changes

2024-10-17 16:07 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
>  |Inform customer||X|
great, thx

2024-10-17 16:08 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +#### Sample Data
great, thx

2024-10-17 16:09 UTC, Frank-Globisch approved these changes
reviewed changes - all remarks covered - thank you.

2024-10-18 06:49 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +Simulated Delta-Production may be used within a Capacity Group to indicate how production can be adjusted to meet demand. It helps cover potential shortfalls by showing where goods could be produced
Resolved via commit 6a6cab3

2024-10-18 06:51 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- No frequent alerting for minor bottlenecks which can be solved by the supplier (within its actual capacity)
Resolved via commit 22c5588

2024-10-21 07:55 UTC, merged