Update load-factors.md
ClosedSourcerer/eclipse-tractusx.github.io pull request #17
Opened 2024-10-02 14:08 UTC by kenobi79

2024-10-02 14:33 UTC, lanfrans commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +| Load Factor | no | If existent, the load factor indicates that this material of the material demand collection takes a factor more or less intensity to produce.| Decimal value (e.g. "3.5"). |
Description not really clear.

2024-10-07 08:52 UTC, ClosedSourcerer requested changes
License Footer does not make sense.
Where is the mention of capgemini?

2024-10-07 08:52 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +Load factors are advanced properties of a Capacity Group structure and therefore used optionally by suppliers. The application of Load factors is embedded into the WeekBasedCapacityGroup aspect model
Concistency:
Here you talk about properties, later on about parameters.

2024-10-07 08:52 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> + "loadFactor"
This aint a valid json.
Do not use CodeBlocks to emphasize a single expression.
"" becomes redundant for emphasize when useing backticks.

`loadFactor`

```
loadFactor
```

2024-10-07 08:52 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +| Load Factor | no | If existent, the load factor indicates that this material of the material demand collection takes a factor more or less intensity to produce.| Decimal value (e.g. "3.5"). |
The property within the aspect model is called loadFactor 

If we add a table using a more business oriented language (parameters) we need to add functional identical tables to the other Use Case pages

2024-10-07 08:52 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![LoadFactor_swimlane](https://github.com/user-attachments/assets/eacbd366-1fe0-40c1-85f8-a421b140d13c)
This will not work.
Pictures need to bee placed into the docs-kits\kits\Demand and Capacity Management Kit\adoption-view\use-case\resources folder in addition to a corresponding license file

2024-10-07 08:52 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![Loadfactor_example](https://github.com/user-attachments/assets/579c1f3f-c218-4d63-9a13-53968bd26769)
See comment above

2024-10-08 10:22 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +| Load Factor | no | If existent, the load factor indicates that this material of the material demand collection takes a factor more or less intensity to produce.| Decimal value (e.g. "3.5"). |
Description changed to: 
"If applied, a load factor indicates that in order to produce the required material demand,  more (or less) production resources are required."

Property/parameter changed to "loadFactor"

2024-10-08 10:23 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +Load factors are advanced properties of a Capacity Group structure and therefore used optionally by suppliers. The application of Load factors is embedded into the WeekBasedCapacityGroup aspect model
License footer: added Capgemini Deutschland GmbH

2024-10-08 10:24 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![LoadFactor_swimlane](https://github.com/user-attachments/assets/eacbd366-1fe0-40c1-85f8-a421b140d13c)
Added all images to /resources incl. license file. Changed all image links to correct path.

2024-10-08 10:24 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![Loadfactor_example](https://github.com/user-attachments/assets/579c1f3f-c218-4d63-9a13-53968bd26769)
Added all images to /resources incl. license file. Changed all image links to correct path.

2024-10-08 11:45 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +Load factors are advanced properties of a Capacity Group structure and therefore used optionally by suppliers. The application of Load factors is embedded into the WeekBasedCapacityGroup aspect model
"properties" changed to "parameters"

2024-10-08 11:48 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> + "loadFactor"
removed json codeblock

2024-10-08 11:52 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +| Load Factor | no | If existent, the load factor indicates that this material of the material demand collection takes a factor more or less intensity to produce.| Decimal value (e.g. "3.5"). |
initial description taken from aspect model, if changed need to sync back w/ aspect model? tbd

2024-10-08 12:08 UTC, ClosedSourcerer commented
> > License Footer does not make sense. Where is the mention of capgemini?
> 
> Added "- SPDX-FileCopyrightText: 2023,2024 Capgemini Deutschland GmbH" to footer

Did you work in 2023 on this?

2024-10-08 12:23 UTC, kenobi79 commented
> > > License Footer does not make sense. Where is the mention of capgemini?
> > 
> > 
> > Added "- SPDX-FileCopyrightText: 2023,2024 Capgemini Deutschland GmbH" to footer
> 
> Did you work in 2023 on this?

I have been working on this since 2018 :-) Will change it.

2024-10-08 12:48 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +Suppliers can use comments to provide customers with additional information about the applied load factors. For more details on this communication feature, see Chapter 5.9 of the CX-0128 DCM Standard
suggested to add a link to DCM standard in the cat-x library.

2024-10-08 12:51 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![Loadfactor](./resources/business-process_LoadFactor_sequence.svg)
I thought sequence diagrams are to be kept in mermaid instead of .svg and only mermaid block diagrams should be replaced with svg ? Needs general clarification in the DCM expert group to be consistent across all new features.

2024-10-08 12:55 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +
as per my understanding from the WS outcome, individual json code examples should be avoided and instead the related aspect model example in the development view should be referenced, i.e. in this case [WeekBasedCapacityGroup](https://eclipse-tractusx.github.io/docs-kits/kits/DCM-Kit/development-view/model-WeekBasedCapacityGroup). 
Refer to the WS documentation on general rules in [MIRO](https://miro.com/app/board/uXjVKkBbvcE=/).

2024-10-08 12:57 UTC, Frank-Globisch requested changes
left individual comments along the document; particularly the last one on how to handle sample data should be updated to stay in sync to general rules agreed in WS and documented in MIRO

2024-10-09 09:18 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +Suppliers can use comments to provide customers with additional information about the applied load factors. For more details on this communication feature, see Chapter 5.9 of the CX-0128 DCM Standard
Totally agree

2024-10-09 09:24 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![Loadfactor](./resources/business-process_LoadFactor_sequence.svg)
Included into Weekly of DCM EG at 11.10.2024

2024-10-09 09:26 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +
Included into Weekly of DCM EG at 11.10.2024

2024-10-11 12:16 UTC, KZI-CatX approved these changes

2024-10-15 08:44 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +Suppliers can use comments to provide customers with additional information about the applied load factors. For more details on this communication feature, see Chapter 5.9 of the CX-0128 DCM Standard
Done

2024-10-15 08:45 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![Loadfactor](./resources/business-process_LoadFactor_sequence.svg)
Re-added mermaid diagram (kept .svg Link commented out)

2024-10-15 08:49 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +
Done

2024-10-15 08:56 UTC, kenobi79 reviewed
Change accepted

2024-10-15 09:02 UTC, kenobi79 reviewed
All changes incorporated

2024-10-15 09:37 UTC, kenobi79 reviewed
All proposed changes adressed and resolved

2024-10-15 11:55 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![LoadFactorLegend](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/blob/DCM-KIT-Load-Factors-Content/docs-kits/kits/Demand%20and%20Capacity%20Management%20Kit/adoption-view/use-case/re
@ClosedSourcerer Same topic with wrong size of the figure legend. Can you please support how to fix. Thanks.

2024-10-15 11:55 UTC, LukasSchmetz approved these changes
LGTM

2024-10-15 12:42 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![LoadFactorLegend](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/blob/DCM-KIT-Load-Factors-Content/docs-kits/kits/Demand%20and%20Capacity%20Management%20Kit/adoption-view/use-case/re
Found a way to scale images, e.g: <img src="https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/blob/DCM-KIT-Load-Factors-Content/docs-kits/kits/Demand%20and%20Capacity%20Management%20Kit/adoption-view/use-case/resources/business-process_FunctionalBlockDiagram_Legend.svg" width="400"> 
Added to features LoadFactors and Delta-Production, let me know if this is s feasible way.

2024-10-15 14:57 UTC, reginePrivat approved these changes

2024-10-15 15:46 UTC, lanfrans commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +| Load Factor | No | If applied, a Load Factor indicates that in order to produce the required material demand,  more (or less) production resources are required.| Decimal value (e.g. "3.5"). A value
Review Example - alternative: "Decimal value (e.g. "3.5"). A value of 3.5 means that in the respective week the demand value is multiplied by 3,5 in order to reflect the required capacity needed to fulfil the demand."

2024-10-15 15:49 UTC, lanfrans commented
Check licenses: should we keep the year 2023?

2024-10-15 15:51 UTC, lanfrans approved these changes
approved - suggestions for minor changed delivered

2024-10-16 07:23 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +| Load Factor | No | If applied, a Load Factor indicates that in order to produce the required material demand,  more (or less) production resources are required.| Decimal value (e.g. "3.5"). A value
Thx Stefania, that sounds better. Have adopted it.

2024-10-16 12:24 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![LoadFactorLegend](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/blob/DCM-KIT-Load-Factors-Content/docs-kits/kits/Demand%20and%20Capacity%20Management%20Kit/adoption-view/use-case/re
Scaling in the deployed KIT work fine.
Please use [!Name](relative Path) for images.
Also the pictures need to be uploaded into the branch correct branch.

2024-10-16 12:48 UTC, kenobi79 commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![LoadFactorLegend](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/blob/DCM-KIT-Load-Factors-Content/docs-kits/kits/Demand%20and%20Capacity%20Management%20Kit/adoption-view/use-case/re
Commented out, re-added relative path and added pictures to correct branch. Please suggest on how scaling should be done correctly (see other comment in DeltaProduction). Thx

2024-10-17 11:31 UTC, ClosedSourcerer requested changes
Please ensure that the License Notice makes sense.
Overwriting previous contributions is not the way to go, to my current knowledge.
This means, that the License notice works addative at best.

Please provide me with the original source for 

`![Loadfactor](./resources/business-process_LoadFactor_example_diagram.svg)`
`Figure: *Example for application of Load Factor within WeekBasedCapacityGroup*`

2024-10-17 11:50 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/delta-production.md
> +- SPDX-FileCopyrightText: 2024 Capgemini Deutschland GmbH
Changing delta-production.md in the load-factors feature branch will only lead to merge conflicts.
Please execute features only within the realm of the specific feature branch.

2024-10-17 12:10 UTC, kenobi79 commented
> Please ensure that the License Notice makes sense. Overwriting previous contributions is not the way to go, to my current knowledge. This means, that the License notice works addative at best.

Sorry but there was no intent to overwrite anything, if there are specific guidelines on how to handle License Notices they should be announced, at least I did not perceive a final decision on that in our last calls.

> Changing delta-production.md in the load-factors feature branch will only lead to merge conflicts.
Please execute features only within the realm of the specific feature branch.

Imo we should think about if we could make this workflow less error prone in future releases.

Source for images sent by email.

2024-10-17 15:53 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +Suppliers can use comments to provide customers with additional information about the applied load factors. For more details on this communication feature, see Chapter 5.9 of the CX-0128 DCM Standard
perfect thanks

2024-10-17 15:54 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +![Loadfactor](./resources/business-process_LoadFactor_sequence.svg)
perfect, thx

2024-10-17 15:56 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/load-factors.md
> +
great, thx

2024-10-17 15:57 UTC, Frank-Globisch approved these changes
Reviewed the requested changes - all covered. Thanks.

2024-10-21 08:35 UTC, merged