DCM KIT Nesting Content
ClosedSourcerer/eclipse-tractusx.github.io pull request #18
Opened 2024-10-04 12:58 UTC by Frank-Globisch

Added nesting as use case in DCM Kit and included updated references and changed break codes

2024-10-07 07:14 UTC, lanfrans approved these changes

2024-10-07 07:59 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +
Please add SVGs for the BLockBeta Code.
Also remeber to add license Files for every picture.

2024-10-07 07:59 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +![Recurrent nested Capacity Groups" src="!](./resources/2024-09-24_DCM_Nesting_example_picture.svg)
License File missing for this picture.
Please Keep the naming scheme consistent with the existing ressources

2024-10-07 07:59 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +```
I do not think that a whole codeblock ``` should be used instead maybe use a single backtick ` to put emphasize on linkedCapacityGroups.

At the same time both the CodeBlock as well as Background make the "" redundant
```
linkedCapacityGroups
```

`linkedCapacityGroups`

2024-10-07 07:59 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +- Capacity Group 1 and 2 are linked to Capacity Group 3 (i.e. Nesting or indirect linking). 
Consistency: 
In the Figure there is no `Capacity Group 1` just a `Capacity Group - 1`

2024-10-07 07:59 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +- Suppliers can use comments to provide customers with additional information about the Nesting. For more details on this communication feature, see Chapter 5.9 in the [CX-0128 DCM Standard document]
chapter not Chapter.
For reference: https://github.com/catenax-eV/cx-ex-dcm/tree/main/CX-0128 x.y is a chapter x.y.z would be a section.

2024-10-07 07:59 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +- Suppliers can use comments to provide customers with additional information about the Nesting. For more details on this communication feature, see Chapter 5.9 in the [CX-0128 DCM Standard document]
`chapter in DCM Kit of Tractus-X.` 
The KIT is not structured into chapters and sections, but rather pages.

2024-10-07 07:59 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +| Main Parameters | Required? | Description | Example |
Just as a comment:
From a technical perspective there is mandatory and optional.

2024-10-09 08:10 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +```
Remark: We decided to fully removed the codeblock in chapter "Load Factors" after Philipps identical comment. Most important thing to stay consistent for all features.

2024-10-09 08:18 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +Nesting is a feature defined in the DCM standard CX-0128 and includes an advanced property of the Capacity Group structure and therefore may be used optionally by suppliers. The application of Nestin
Add direct Link to CX-0128?

2024-10-09 08:20 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +Nesting is a feature defined in the DCM standard CX-0128 and includes an advanced property of the Capacity Group structure and therefore may be used optionally by suppliers. The application of Nestin
"The application of Nesting" => Vorschlag "The Nesting feature"

2024-10-09 08:24 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +## Business value
Consistency in headlines (e.g. "Business Roles and Functions" vs. "Business value" => Proposal to use capital letters "Business Value","Functional Description" etc

2024-10-09 08:26 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +```
Proposal to integrate it as a parameter table like in the other features and aligned in workshop

2024-10-09 08:42 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +
i.e. can be removed within the brackets from my point of view. "." to be used or removed for all bullet points to keep it consistent.

2024-10-09 08:54 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +Figure: *Example for application of Nesting*
svg to be integrated as currently no figure to be seen

2024-10-09 09:08 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +![Recurrent nested Capacity Groups" src="!](./resources/2024-09-24_DCM_Nesting_example_picture.svg)
@ClosedSourcerer  License File issue solved?

2024-10-09 09:10 UTC, MWADCM commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +- Capacity Group 1 and 2 are linked to Capacity Group 3 (i.e. Nesting or indirect linking). 
Classical Mistake. Need to be corrected.

2024-10-11 12:15 UTC, KZI-CatX approved these changes

2024-10-11 12:28 UTC, ClosedSourcerer requested changes
Found additional stuff, please adress.

2024-10-11 12:28 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +
Maybe remove the breaks?
Do we really need them outside of tables?

2024-10-11 12:28 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +<br/><br/>
Another break

2024-10-11 12:30 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +
Fixed it via commit: https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/pull/18/commits/c7d7188e09d84bea76888b2f0ab5beb1461f10c7

2024-10-11 12:32 UTC, sarahmater approved these changes

2024-10-11 13:44 UTC, MWADCM approved these changes

2024-10-14 12:19 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +Nesting is a feature defined in the DCM standard CX-0128 and includes an advanced property of the Capacity Group structure and therefore may be used optionally by suppliers. The application of Nestin
Updated wording as suggested.

2024-10-14 12:44 UTC, Frank-Globisch reviewed
Updated nesting.md based on several review comments (not completely yet).

2024-10-14 12:44 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +## Business value
Updated in PR [https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/commit/a99a7ba9bef353b87f35013562f173b7ec0e5017](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/commit/a99a7ba9bef353b87f35013562f173b7ec0e5017)

2024-10-14 12:44 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +```
The parameter table is already available further below in the description. Therefore I only changed the codeblock to a single backtick as suggested. PR [https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/commit/2342a507fc08bbd637203a30b0dab373eaf4867e](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/commit/2342a507fc08bbd637203a30b0dab373eaf4867e)

2024-10-14 12:44 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +
SVGs were inserted via PR [https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/commit/b1d90cef92d3e13caa9c9a20b83488417ee951ed](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/commit/b1d90cef92d3e13caa9c9a20b83488417ee951ed). I noticed that the coloring doesn't fit completely, thus will not mark it as resolved yet.

2024-10-15 12:40 UTC, ClosedSourcerer commented
> Updated nesting.md based on several review comments (not completely yet).

The inserted SVGs are no vectorgraphics, but rather base 64 jpegs embedded into an SVG file --> They do not scale.
Please add true scalable vector graphics.

2024-10-16 13:51 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +
SVGs with correct transparency and colors as well as fitting font size were uploaded together with license files.

2024-10-16 14:01 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +![Recurrent nested Capacity Groups" src="!](./resources/2024-09-24_DCM_Nesting_example_picture.svg)
Updated picture with naming scheme was uploaded a few days back 
License file was added today [https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/pull/18/commits/fa0c140c9314cd03e0b1b40bee65123a076f4beb](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/pull/18/commits/fa0c140c9314cd03e0b1b40bee65123a076f4beb)

2024-10-16 14:09 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +- Suppliers can use comments to provide customers with additional information about the Nesting. For more details on this communication feature, see Chapter 5.9 in the [CX-0128 DCM Standard document]
Updated in PR [https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/commit/f5df057e5071fb84e7e8b2cb074e66e7b9dec852](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/commit/f5df057e5071fb84e7e8b2cb074e66e7b9dec852)

2024-10-16 14:10 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +| Main Parameters | Required? | Description | Example |
Understand, however checking in other branches I noticed that they also still now use "Yes" and "No", thus no change.

2024-10-16 19:52 UTC, Frank-Globisch commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/use-case/nesting.md
> +- Capacity Group 1 and 2 are linked to Capacity Group 3 (i.e. Nesting or indirect linking). 
Please check - IMO this is resolved with the past updates to the svg pictures. Latest svg update PR [https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/pull/18/commits/7f673c81012479cf5d4f22f8c789c287eecee25f](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/pull/18/commits/7f673c81012479cf5d4f22f8c789c287eecee25f)

2024-10-17 07:34 UTC, AnastasiaNogay commented
looks good.

2024-10-17 10:35 UTC, ClosedSourcerer requested changes
Please have a close look at every single license notice.

1. Which companies did actually contribute to nesting in an IP-worthy way?
2. I edited the notice within nesting.md, expressing my very generous perception.

The SVGs. do not use the Font Manrope.

1. Please provide me with the original file (for svgs that are not derived from mermaid code) and i will make the appropriate changes as well as save the source file to expert group github for further use

@Frank-Globisch

2024-10-17 14:58 UTC, LukasSchmetz approved these changes
LGTM

2024-10-17 15:44 UTC, Frank-Globisch commented
> Please have a close look at every single license notice.
> 
> 1. Which companies did actually contribute to nesting in an IP-worthy way?
> 2. I edited the notice within nesting.md, expressing my very generous perception.
> 
> The SVGs. do not use the Font Manrope.
> 
> 1. Please provide me with the original file (for svgs that are not derived from mermaid code) and i will make the appropriate changes as well as save the source file to expert group github for further use
> 
> @Frank-Globisch

Hi @ClosedSourcerer ,
original file was shared with you via email a few minutes ago as requested.
As for the notice: I'm fine either way, however I had updated the notice just yesterday after alignment with @LukasSchmetz and thus I think it would be good to have a general rule how to specify the licence notice. Maybe this can be clarified in our weekly call tomorrow ?

2024-10-18 06:40 UTC, AnastasiaNogay approved these changes
reviewed, looks perfect.

2024-10-21 08:07 UTC, merged