DCM KIT Onboarding Content Update
ClosedSourcerer/eclipse-tractusx.github.io pull request #21
Opened 2024-10-14 11:05 UTC by sarahmater

Added updated Onboarding Content from PI 14

2024-10-14 11:38 UTC, ClosedSourcerer requested changes
LIC file for picture missing
Picture is a png not an svg
License Notice says BearingPoint worked on this in 2023?

2024-10-14 11:38 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/onboarding.md
> +
Page is broken because of these 2 lines.
Delete them.

2024-10-14 11:38 UTC, ClosedSourcerer commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/onboarding.md
> +![DCM_Onboarding](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/blob/DCM-KIT-Onboarding-Content---Update/docs-kits/kits/Demand%20and%20Capacity%20Management%20Kit/adoption-view/resour
This is not a SVG.
Also this link will not work once the KIT is deployed.
Try: `![DCM_Onboarding](./resources/DCM_Onboarding.png)`

2024-10-16 14:53 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/onboarding.md
> +
Fixed with commit 69f2ec7

2024-10-16 14:53 UTC, LukasSchmetz commented on docs-kits/kits/Demand and Capacity Management Kit/adoption-view/onboarding.md
> +![DCM_Onboarding](https://github.com/ClosedSourcerer/eclipse-tractusx.github.io/blob/DCM-KIT-Onboarding-Content---Update/docs-kits/kits/Demand%20and%20Capacity%20Management%20Kit/adoption-view/resour
fixed via commit 69f2ec7

2024-10-17 08:23 UTC, LukasSchmetz commented
> LIC file for picture missing Picture is a png not an svg License Notice says BearingPoint worked on this in 2023?

License Note updated and 2023 removed overall with commit 4d06cac
@sarahmater: Is the topic with svg conversion fixed with the colleagues from the team?

2024-10-17 08:27 UTC, LukasSchmetz approved these changes
Really like the visualization and LGTM. Pending topic is the .svg creation we will clarify in parallel.

2024-10-17 12:36 UTC, ClosedSourcerer requested changes
@sarahmater
PLease provide me with the source file of:

`![DCM_Onboarding](./resources/DCM_Onboarding.png)`

2024-10-18 07:44 UTC, reginePrivat approved these changes

2024-10-21 10:06 UTC, merged